# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyvisa as visa


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(509, 72)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 311, 20))
        self.lineEdit.setInputMask("")
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 30, 131, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setText(_translate("MainWindow", "address"))
        self.label.setText(_translate("MainWindow", "Enter instrument address here:"))
        self.pushButton.setText(_translate("MainWindow", "Connect"))


def click():
    try:
        rm = visa.ResourceManager()
        print("list of resourses:", rm.list_resources())
        Infiniium = rm.open_resource(ui.lineEdit.text())
        Infiniium.timeout = 20
        Infiniium.query_delay = 1
        Infiniium.clear()
        Infiniium.term_chars = ""
        # Infiniium.chunk_size = 128
        Infiniium.read_termination = '\n'
        Infiniium.write_termination = '\0'
        Infiniium.baud_rate = 57600
        ui.label.setText("Connected")
    except Exception as e:
        print('[!] Exception:' + str(e))
        # sys.exit()
        return
    
    try:
        print(Infiniium.query("*IDN?"))
    except:
        print("can't ping")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ui.pushButton.clicked.connect(click)
    sys.exit(app.exec_())
